feat: add header
sholq/LabITMO pull request #1
Opened 2022-03-30 11:59 UTC by xZio

Add:
-header logo
-burger-button

2022-03-30 12:28 UTC, sholq commented on pages/index.css
> +  color: #ffffff;
Править что-то в чужом коде не входило в твои задачи.

2022-03-30 12:28 UTC, sholq commented on index.html
> +  <head>
Править что-то в чужом коде не входило в твои задачи.

2022-03-30 12:32 UTC, sholq commented on pages/index.css
> +  margin-left: 77px;
Центрирование лучше выполнить с помощью флексов

2022-03-30 12:41 UTC, sholq commented on pages/index.css
> +  height: 40px;
Размеры несоотвествуют макету. Там 26px*26px, сами линии 20px шириной.

2022-03-30 12:45 UTC, sholq commented on index.html
> +        <img
Давай порядок поменяем, в десктопе порядок друго: <img>, <nav>, <button>.

2022-03-30 13:02 UTC, sholq requested changes

2022-03-30 13:02 UTC, sholq commented on index.html
> +        <img
Давай порядок поменяем, в десктопе порядок друго: img, nav, button.

2022-03-30 13:02 UTC, sholq commented on pages/index.css
> +  margin-left: 77px;
Центрирование лучше выполнить с помощью флексов в .header

2022-03-30 13:02 UTC, sholq commented on pages/index.css
> +  height: 40px;
Размеры несоотвествуют макету. Там 26px*26px, сами линии 20px шириной.

2022-03-30 13:02 UTC, sholq commented on pages/index.css
> +  margin-left: 8px;
Лучше вырвать кнопку из потока и спозиционировать с помощью свойства left. Центрирование по вертикали выполняет align-items из .header

2022-04-21 07:31 UTC, sholq commented
@RusKutuz это ты подтянул что-то в ветку или что?

2022-04-23 19:56 UTC, RusKutuz commented
> @RusKutuz это ты подтянул что-то в ветку или что?



> @RusKutuz это ты подтянул что-то в ветку или что?

Ага, увидел что в девелопе уже прописаны стили и подтянул чтоб не дублировать

2022-04-25 07:21 UTC, sholq commented
Вот эта часть тоже к header относится. Доделай, пожалуйста.

![image](https://user-images.githubusercontent.com/93184424/165039665-68ad7a7a-9ef7-45c8-b967-c5cdd4b24553.png)

2022-05-03 18:22 UTC, RusKutuz commented
> Вот эта часть тоже к header относится. Доделай, пожалуйста.
> 
> ![image](https://user-images.githubusercontent.com/93184424/165039665-68ad7a7a-9ef7-45c8-b967-c5cdd4b24553.png)

доделал

2022-05-04 09:00 UTC, sholq requested changes
Оставил комметарии. Нужно кое-что поправить

2022-05-04 09:00 UTC, sholq commented on index.html
> +        <nav class="menu menu_style_popup">
Чтобы все работало как надо, необходимо классу menu прописать следующие свойства:

![image](https://user-images.githubusercontent.com/93184424/166650483-c5998254-64b5-4dc4-a431-3dab6e24e790.png)

Если ты сейчас включишь свойство display у меню, то все сломается. Нужно вытащить его из потока и спозиционировать.

Поправь это, пожалуйста.

2022-05-04 09:00 UTC, sholq commented on pages/index.css
> +  background-color: transparent;
добавь `cursor: pointer;`

2022-05-04 09:00 UTC, sholq commented on pages/index.css
> +  font-family: "Open Sans", Arial, sans-serif;
Шрифты наследуются от стилей страницы. Это нужно удалить

2022-05-04 09:00 UTC, sholq commented on pages/index.css
> +  font-family: "Open Sans", Arial, sans-serif;
Здесь тоже стоит удалить

2022-05-04 09:00 UTC, sholq commented on pages/index.css
> +  font-style: normal;
Это тоже нужно удалить. Ты явно задаешь значение "по умолчанию"

2022-05-04 09:00 UTC, sholq commented on pages/index.css
> +  font-style: normal;
Удалить

2022-05-04 09:00 UTC, sholq commented on pages/index.css
> +  font-family: "Open Sans", Arial, sans-serif;
Удалить

2022-05-04 09:00 UTC, sholq commented on pages/index.css
> +  font-style: normal;
Удалить

2022-05-07 10:51 UTC, sholq approved these changes
Принято, заливаю

2022-05-07 10:52 UTC, merged