Добавление попапа навигации
sholq/LabITMO pull request #2
Opened 2022-04-01 11:51 UTC by Semen1996

Добавил попап навигацию для мобильной версии

P.S. Получилось почти всё осуществить с помощью css, но снизить прозрачность элементов навигации при нажатии на Образование можно только с помощью js, так как в css нет возможности придать прозрачность всем элементам при нажатии на кнопку. В JS мы просто добавим класс '.menu__list-item_inactive' при нажатии на кнопку

2022-04-02 15:12 UTC, sholq commented on index.html
> +        <nav class="menu menu_style_popup">
Сразу поправишь?

2022-04-02 15:45 UTC, sholq requested changes
Визуально - супер. Но стоит поработать на тегами и иерархией.

2022-04-02 15:45 UTC, sholq commented on index.html
> +            <a href="#" class="menu__list-item"><p class="menu__text">О нас</p></a>
Для ненумерованного списка существует семантический тэг ul, а для элементов списка li.

Для выпадающего списка подэлементов стоит, конечно, использовать какую-то дополнительную обертку.

Также здесь лишняя вложенность - тег p и класс лишние. Текст можно вписать в тег a.

2022-04-02 15:45 UTC, sholq commented on index.html
> +            <label for="tab-education" class="menu__list-item menu__list-item_label"><p class="menu__text">Образование</p></label>
Также лишняя вложенность

2022-04-02 15:45 UTC, sholq commented on index.html
> +            <input class="menu__checkbox" id="tab-education" type="checkbox">
Решение через checkbox изящное, конечно, но стоит поработать над иерархией элементов. Сейчас блок с реализацией подсписка лежит в одной куче со всеми остальными элементами основного списка. Включение тегов ul и li решит эту проблему, но стоит еще подумать на тем, чтобы решение стало более тиражируемым и изящным.

Вообще оптимальным мне кажется решение, когда навигационное меню собирается скриптом автоматически из имеющейся в разметке иерархии заголовков (h1, h2, h3) и нескольких шаблонов template. Такое решение позволяет добавлять на страницу новые разделы и элементы без дополнительной работы руками над навигацией.

2022-04-02 15:45 UTC, sholq commented on index.html
> +          <div class="menu__list">
Надеюсь, ты помнишь, что мы хотим этот же элемент навигационного меню потом использовать на больших разрешениях. Стоит сразу наметить механизм этого превращения и разрабатывать разметку в этом направлении.

Мы можем это обсудить отдельно на общем созвоне или в частном порядке.

2022-04-02 15:45 UTC, sholq commented on pages/index.css
> +.menu__checkbox:checked ~ .menu__list_type_education {
Хорошее решение. Визуально анимация хороша.

2022-04-04 12:26 UTC, Semen1996 commented on index.html
> +        <nav class="menu menu_style_popup">
Поправлю сразу

2022-04-05 08:31 UTC, sholq requested changes
Осталось совсем немного и будем мержить.

Не забудь весь этот блок спрятать пока (display: none). По готовности шапки напишем первый скрипт и установим слушателя на кнопку.

2022-04-05 08:31 UTC, sholq commented on index.html
> +            <li class="menu__list-item"><label for="tab-education" class="menu__text menu__text_type_label">Образование</label></li>
Осталось немного довести до конца.

Вот мой эскиз: https://codepen.io/sholq/pen/wvpywqd

Стилизованно у тебя было хорошо, нужно оставить эти эффекты, доработав под новую иерархию. Я по ссылке выше демострирую только необходимую иерархию, теги и возможные классы со стилями.

В будущем, когда будем делать JS, откажемся от чекбокса.

2022-04-05 13:57 UTC, merged