feat: добавить карточку о нас
sholq/LabITMO pull request #4
Opened 2022-04-01 18:06 UTC by Aksenov-m

Добавил карточку о нас

2022-04-02 16:45 UTC, sholq requested changes
Оставил свои комментарии.

2022-04-02 16:45 UTC, sholq commented on index.html
> +    <meta charset="UTF-8" />
Как я понимаю, у тебя включен сторонний плагин, которые автоматически форматирует код добавляя отступы и другое. Думаю, при работе в команде от такого стоит отказаться, так как ты берешь файл, в котором должен сверстать одну секцию, а в итоге изменяешь все остальные строки.

Попробуй в следующем коммите это исправить. Я, как ревьюер или твой коллега, хочу видеть изменения только в твоей секции или видеть свой код нетронутым чужими коммитами.
![изображение](https://user-images.githubusercontent.com/93184424/161392148-ef4cd96a-e20c-43b6-99ff-115837ee6f09.png)

2022-04-02 16:45 UTC, sholq commented on index.html
> +          <article class="card">
Супер - семантический тэг!

Думаю, можно сразу добавить теги ul и li, так как это в любом случае будет ненумерованный список из таких карточек.

2022-04-02 16:45 UTC, sholq commented on index.html
> +        <section class="description">
В этой же секции присутствуют заголовок и текст. Наверное, мы друг друга недопоняли при выдаче задания.
![изображение](https://user-images.githubusercontent.com/93184424/161392260-14bbfde4-6a56-46b8-8c21-ff4a050309bd.png)

2022-04-02 16:45 UTC, sholq commented on index.html
> +            <h2 class="card__description">
Используй тег p

2022-04-02 16:45 UTC, sholq commented on index.html
> +              НОВИЧК…
Автоматическое добавление троеточия "..." при переполнении блока реализовывалось в одном из первых спринтов проекта Mesto.

Идея в том, чтобы не думать о таких вещах при добавлении новых карточек на страницу. Не должен условный SMMщик добавлять в текст символы "&nbsp;" и "...". Заголовок в разметке и стилях должен быть описан так, что текст автоматически переносится на новую строку до определенного момента, а затем переполняется - появляется "..."

Это мы реализовывали в проектной работе четвертого спринта. Прямо в задании к ней ты найдешь подсказку.

2022-04-02 16:45 UTC, sholq commented on index.html
> +              Команда ИТМО стала лучшей&nbsp;на международном финале
Зачем все эти символы в разметке?

Мы не стремимся к тому, чтобы все выглядело как на макете, а пытаемся сделать работоспособный и тиражируемый шаблон для карточек. Нужно описать этот блок в разметке и стилях так, чтобы текст форматировался автоматически. 

Мы не стремимся к тому, чтобы у нас были переносы текста в тех же местах, что и макете.

2022-04-02 16:45 UTC, sholq commented on index.html
> +            <img class="card__pin" src="./image/pin.svg" alt="" />
Так как изображение пина не несет на себе никакой смысловой нагрузки, то стоит перенести его в свойство background-image класса, а в разметке использовать тэг div.

2022-04-04 12:18 UTC, sholq commented on index.html
> +              Команда ИТМО стала лучшей&nbsp;на международном финале
Поясни, пожалуйста, что за "типограф". Сторонний плагин?

2022-04-04 12:22 UTC, Aksenov-m commented on index.html
> +              Команда ИТМО стала лучшей&nbsp;на международном финале
https://www.artlebedev.ru/typograf/ Типограф ставит неразрывные пробелы. Я уже удалил их

2022-04-04 13:16 UTC, sholq commented on index.html
> +        <h1 class="description__title">несколько слов о нас</h1>
Смотри следующий коментарий

2022-04-04 13:25 UTC, Aksenov-m commented on index.html
> +                <h2 class="card__title">авторы робота-музыканта роберта роботецкого признаны лучшими новичком</h2>
ок. исправлю

2022-04-05 06:59 UTC, sholq approved these changes
Супер, будем мержить

2022-04-05 07:00 UTC, merged