Feat/partners
sholq/LabITMO pull request #8
Opened 2022-04-15 09:11 UTC by RusKutuz

Привет. Прошу проверить блок Partners

2022-04-15 09:51 UTC, sholq commented
Сразу замечание по именам коммитов. Мы следуем Соглашению о Коммитах или хотя бы уроку Идеальный Коммит из курса.

2022-04-15 09:56 UTC, sholq commented
Первые два коммита совсем пустые. Зачем их нужно было отделять?

Во втором коммите помимо изменений в секции ты правишь что-то в чужой части кода. Так делать тоже не стоит.

2022-04-15 09:59 UTC, sholq commented
Всё это зальется в историю коммитов ветки develop, а потом в main и будет висеть в наших портфолио.

Лучшим решением будет откатить коммиты в ветке и сделать один коммит с готовой версткой. Имя коммита должно отражать содержание, а содержание не должно выходить за рамки, которые ты декларируешь в имени. Например, "feat: add Partners section"

2022-04-18 16:55 UTC, sholq requested changes
Супер! Но нужно кое-что поправить

2022-04-18 16:55 UTC, sholq commented on index.html
> +        <h2 class="partners__header">С КЕМ МЫ РАБОТАЕМ</h2>
Сделай это этой части секции обертку. У секции должно остаться 2 дочерних элемента: контейнер и список.

2022-04-18 16:55 UTC, sholq commented on index.html
> +            <a href="#" target="_blank">
Думаю, можно дать ссылки на официальные сайты компаний.

2022-04-18 16:55 UTC, sholq commented on pages/index.css
> +  margin: 8px 5px;
Задай у контейнера padding, высоту и выравнивание по вертикали. Тогда можно вообще отказаться от стилей элементов.

Например:
    .partners__links {
        margin: 28px 0 0;
        height: 100px;
        box-sizing: border-box;
        padding: 0 5px;
        align-content: space-between;
        display: flex;
        flex-flow: row wrap;
        justify-content: space-between;
        align-items: flex-end;
        list-style: none;
    }

Не забудь проверить на на PixelPerfect.

2022-04-18 21:57 UTC, RusKutuz commented on index.html
> +        <h2 class="partners__header">С КЕМ МЫ РАБОТАЕМ</h2>
done

2022-04-18 21:57 UTC, RusKutuz commented on index.html
> +            <a href="#" target="_blank">
done

2022-04-18 21:57 UTC, RusKutuz commented on pages/index.css
> +  margin: 8px 5px;
done

2022-04-19 08:06 UTC, sholq requested changes
Поправь тег обертки, пожалуйста.

2022-04-19 08:06 UTC, sholq commented on index.html
> +        <article class="partners__article">
Тег article несет на себе слишком большую семантическую нагрузку для простой обертки. Этим тегом обычно обрамляют независимые блоки контента, а здесь мы просто сепарируем части секции. 

Если бы это был действительно блок article, то ему бы стоило задать заголовок h3, но так как мы внутрь помещаем заголовок section h2, то стоит использовать обычный div. А класс назвать "partners__container" или "partners__wrap"

2022-04-20 06:53 UTC, sholq approved these changes
Супер!

2022-04-20 06:53 UTC, merged