Feat/form
sholq/LabITMO pull request #9
Opened 2022-04-20 16:51 UTC by Semen1996

Ошибки валидации не прописывал, потому что нигде не указано: как они должны выглядеть.

Шаблон номера (а-ля +7 (911) 222-22-22) потом можно будет установить с помощью js (Ну чтобы когда нажимал на поле ввода, плейсхолдер убирался и появлялся шаблон +7 (___) ___-__-__)

2022-04-21 07:29 UTC, sholq requested changes
Оставил комментарии.

2022-04-21 07:29 UTC, sholq commented on index.html
> +            <input id="surname" class="form__input form__input_type_surname"  type="text" value="" placeholder="Фамилия" required>"\+79[0-9]{9}|8[0-9]{10}"
Оставил лишнее после тега "\+79[0-9]{9}|8[0-9]{10}"

2022-04-21 07:29 UTC, sholq commented on index.html
> +            <input id="name" class="form__input form__input_type_name"  type="text" value="" placeholder="Имя" required>
Мне кажется, лучше использовать вместо id атрибут name.

2022-04-21 07:29 UTC, sholq commented on pages/index.css
> +
Много пустых линий

2022-04-21 07:29 UTC, sholq commented on index.html
> +          <h2 class="form__title">ВСЕГДА НА СВЯЗИ</h2>
Заголовок и описание стоит вынести из тега form и поместить в обертку.

2022-04-21 07:29 UTC, sholq commented on index.html
> +        <form class="form__container" name="connect">
Неудачно мы выбрали название для секции. 

Давай переменуем так, чтобы тег формы имел классы типа "form form_type_request", а блок секции назовем соответсвенно "request". Если есть варианты удачнее, то предлагай. 

Для формы добавил модификатор, потому что, может быть, стоит заранее отделить общие для всех форм стили от стилей конкретно этой формы (хотя в макете таких нет, но вдруг когда-нибудь появились бы).

2022-04-22 18:20 UTC, Semen1996 commented on index.html
> +            <input id="name" class="form__input form__input_type_name"  type="text" value="" placeholder="Имя" required>
В 6 спринте  в разделе "Добавление span ошибки" предлагается вариант с id ( https://practicum.yandex.ru/learn/web/courses/35d951a1-b62c-4a96-96ac-a8118657fad0/sprints/23854/topics/67ecb44c-7b35-47d5-9832-a5ca7229f0b3/lessons/b3618937-a4eb-48ac-be0e-2eeea9468bf0/ )

2022-04-22 18:28 UTC, Semen1996 commented on index.html
> +        <form class="form__container" name="connect">
Предлагаю назвать секцию feedback. Это же типа форма обратной связи всё-таки

2022-04-22 18:49 UTC, Semen1996 commented on index.html
> +          <h2 class="form__title">ВСЕГДА НА СВЯЗИ</h2>
А разве нельзя оставить так?

 Просто там зазоры между заголовком, описанием, полями и кнопкой ОТПРАВИТЬ одинаковые (23px- в мобильной верстке, и в других верстках тоже имеют одинаковые значения). Получается, что данный вид самый оптимальный

2022-04-25 07:04 UTC, sholq commented on index.html
> +            <input id="name" class="form__input form__input_type_name"  type="text" value="" placeholder="Имя" required>
Ок, тогда валидация за тобой будет

2022-04-25 07:10 UTC, sholq commented on index.html
> +          <h2 class="form__title">ВСЕГДА НА СВЯЗИ</h2>
Как я понял из ревью своих проектных работ, лучше в тег form не включать ничего лишнего - только атрибуты формы.

Это пока что они одинаковые =) перелопачивать придется больше если будут правки в макет.

2022-04-25 07:13 UTC, sholq commented on index.html
> +          <h2 class="form__title">ВСЕГДА НА СВЯЗИ</h2>
Я сторонник того, чтобы иерархически структуировать элементы.

Секция имеет заголовок второго уровня (заголовок секции), описание и форму. Форма имеет поля ввода, лейблы и тд.

Если хочешь, можешь обойтись без обертки, но заголовок и описание нужно вынести из формы.

2022-04-25 07:16 UTC, sholq commented on index.html
> +        <form class="form__container" name="connect">
Feedback это про отзыв, мне кажется. А тут именно запрос на отклик.

Выбирай любой вариант

2022-05-02 14:55 UTC, sholq requested changes
Посмотри замечание и будем заливать.

2022-05-02 14:55 UTC, sholq commented on index.html
> +        <div class="request__container">
Контейнер я имел в виду только для заголовка и описания.

Посмотри как сделали в другой секции Лаборатория:
https://github.com/sholq/LabITMO/blob/develop/index.html

2022-06-01 18:57 UTC, merged